language: cpp
sudo: required
dist: trusty
compiler:
- clang
- gcc
env:
- TEST_TYPE=Debug
- TEST_TYPE=Release
install:
- ./scripts/install_dependencies.sh
before_script:
- export PATH="/usr/bin:$PATH"
- ./scripts/print_diagnostics.sh
script:
- env && rm -rf build && ./scripts/build.sh "$TEST_TYPE" 1 && (cd build && make test)
