language: cpp
sudo: required
dist: trusty
install:
- ./scripts/install_dependencies.sh
before_script:
- export PATH="/usr/bin:$PATH"
- ./scripts/print_diagnostics.sh
script:
- rm -rf build && ./scripts/build.sh "$TEST_TYPE" 1 && (cd build && make test)
env:
- TEST_TYPE=Debug
- TEST_TYPE=Release
- CC=clang CXX=clang++
- CC=gcc CXX=g++
